### PR TITLE
Change local search engine installation.

### LINKED ISSUE #16: Switch from elastic search implementation to open search
standing issue from weekly meeting seems to be open search local deployment not having support for MacOS. 

Potential solution proposed was a docker image

### PR DESCRIPTION
**Pull request by ronitagarwala01**
Change local search engine from ElasticSearch to OpenSearch. Note that OpenSearch's security plugin is disabled during local development.

Fixes #16.

### CODE REVIEW

**Review by lpsinger — CHANGES_REQUESTED** [review]
You removed the command-line flag `-Expack.security.enabled=false` and added a YAML configuration file. Is that command-line flag not supported in OpenSearch?

**Comment by ronitagarwala01** [comment]
No that specific command is not supported in opensearch. Also I didn't add the yaml file, it comes with the local installation of opensearch. I just wrote to it to disable the security plugin.

**Comment by lpsinger** [comment]
Right, but you can control this setting from the command line using `-Eplugins.security.disabled`. Please pass the configuration variables on the command line. Let's not modify any of the files from the OpenSearch distribution if we can avoid it.

**Comment by ronitagarwala01** [comment]
Ok I just removed it.

**Comment by lpsinger** [comment]
Yes, but you need to add it to the command line arguments.

**Comment by ronitagarwala01** [comment]
You're right. Just fixed.

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
